name = "10x-cards"
compatibility_date = "2024-05-31"

# KV namespace for Astro sessions
[[kv_namespaces]]
binding = "SESSION"
id = "f794926bb8ab40199bda3c297d8fd94c"
preview_id = "fca2f929bb6e4558a568c2bcadb5b522" 